### ISSUE TITLE
Major Feature Requests

### ISSUE THREAD

**Issue by Krutoy242** [ProjectHDS/JEIExporter#1]
I have deal with @GBLodb to join forces.
- I will make my [CraftTree project](https://krutoy242.github.io/CraftTreeVisualizer) display the crafting tree for the Herodotus modpack.
- The HDS team will help me with exporting recipes from mintcraft.

![Example of recipes tree](https://i.imgur.com/swXN4CP.png)

The idea is that it would be hard to inject into each mod individually to extract recipes from each individual machine, so the best way is to use JEI and its API (i guess?).

### CraftTree Working Principles

A little bit about how my **CraftTree** project works.

Its main task is not only to show the **crafting chains**, but also to calculate the [complexity of items](https://i.imgur.com/dyhj4tC.png).
> **Complexity** means "how much effort you need to get this item". Its relatively equal to UU-Matter cost from IC2 mod.

To do this, besides the usual information about items (name, icon), the program needs to supply all the **connections between items** in the game.

All recipes in Minecraft can be unified to the following form:
- 📦 Output ItemStacks
- 🟦 Consumed Ingredients
- ⚙️ Non-Consumed ingredients (a.k.a "Catalyst")

The goal of JEIExporter is to provide as much information of this kind as possible.

# TODO

**JEIExporter** already has several features that are great for the task, such as category names, icon and recipe export. But more is needed.

## Important

Changes that need to be done in first order.

- [x] Output every custom JEI `IIngredientType`.
  > Things like Gas from Mekanism or IE Multiblock placeholders should be present as inputs / outputs / catalysts.  
  > Right now they are not outputted at all as inputs / outputs and outputted as classpath when catalyst.  
  > ![](https://i.imgur.com/ShsO1oc.png)
  > Syntax should be universal, probably `{resource_type}:{registry_name}`, for example `gas:chlorine` or `skill:intelligence`

- [x] Output items as Oredict when ingredient is oredicted.
  > Right now all possible items expanded as list. Should be `ore:blockGold`:  
  > ```json
  > "items": [
  >   {
  >     "amount": 1,
  >     "stacks": [
  >       {"name": "minecraft:gold_block:0"},
  >       {"name": "chisel:blockgold:0"},
  >       {"name": "chisel:blockgold:1"},
  >       ...
  > ```

- [x] NBT tags should be delivered with items / fluids.
  > Example: `fluid:potion{Potion:"minecraft:haste"}`.
  >
  > Note that some items like default Tinkers' Constructs tools ⛏️ or Forestry Bees 🐝 have huge item data in serialized form.  
  > Probably, Exporter need some kind of caching this NBT data to make it reusable, OR make other mechanics to store it separately from items.

- [x] Blacklist exporting JEI categories in JEIExporter config list
  > Some categories not shows actual recipes, like Banners or Actually Additionals book entries.  
  > `.cfg` file could content:
  ```
    S:category_blacklist <
      lx_jei_banner_pattern_shapes
      lx_jei_banner_pattern_symbols
    >
  ```

## Secondary

Not so important but preferably.

- [x] ~~Output wildcarded metadata as `*`.~~
  > ~~Right now `minecraft:dye:32767` should be `minecraft:dye:*` since metadata here stored as string~~

- [ ] Output additional data printed in JEI
  > This includes important text or numbers, like drop chance in Block Drops tab.  
  > Ideally all information that changes item cost should be outputted.  
  > ![](https://i.imgur.com/2y6Beyi.png)

- [x] Option to disable creating `.png` textures
  > This could reduce exporting time when we don't need to recreate images.

- [x] Output positions of input / output slots
  > This could be needed if i would decide to copy JEI interface in web browser application.

- [ ] Filtering subcategory
  > Some JEI categories flooded with non-progression related recipes, like filling every tank with every liquid, like TE's Fluid Transposer do.
  > This "subcategories" should be outputted separately and have blacklist feature.
  > ![](https://i.imgur.com/DYvGl8u.png)

- [x] Attach item Tooltips with name
  > Sometimes, item names are the same, and only tooltip is different (usually based on NBT tags or meta).  
  > This could lead to unclear results, when different definition+meta items called the same, like chiseled blocks.  
  > This could be optional only for items with same name.
  > ![All this blocks called "Antiblock"](https://i.imgur.com/Jqp3cxf.png)

- [x] Add lossless item icons name exporting
  > Right now `:` serialized into `_`. Underscore can be used for item id, that could make problems on deserializing string into `mod:name:meta` form.
  > `__` could be used instead, or even another symbol, that valid for file name but invalid for item registry.

- [x] Log export category __before__ it starting to export, instead of after exporting done
  > Right now logging writes 
  ```cs
  [jeiexporter]: Saved category: Industrial Foregoing's Manual
  ```
  > When crash occur its unable to understand what category crashed. If category id, same as in "blacklist" option, would be written in log, users can add it to blacklist to avoid crash. For example:
  ```cs
  [jeiexporter]: Begin saving category: [if_manual_category] Industrial Foregoing's Manual 
  ```

--------------

**Comment by friendlyhj** [comment]
> Output wildcarded metadata as *.
> 
> Right now minecraft:dye:32767 should be minecraft:dye:* since metadata here stored as string

No. 32767 is used as meta wildcard. And `*` is invalid for file names. Use `*` in recipe jsons but `32767` in icons? I don't think it is a good idea.

**Comment by Krutoy242** [comment]
### Is it possible to not add tag for ingredients that not require it?

I found that some recipes has ingredients with NBT data, but actually they don't need that NBTs.

For example, this native Actually Additions recipes shows full battery, but in crafting table any charge match:

![](https://i.imgur.com/McZOTVY.png)

![](https://i.imgur.com/rWsn4LY.png)

I don't know how its working inside, but i used this option from CraftTweaker too.
According to [docs](https://docs.blamejared.com/1.12/en/Vanilla/Items/IItemStack#tags), there is `matchTagExact` option that could be used to this trick - in JEI it would show item with tag, but in crafting table tag wont matter:
```less
stack.withTag(IData tag, bool matchTagExact)
```

Since JEIExporter output recipes, it would be better if it would not add tags to items, that not require it.

**Comment by friendlyhj** [comment]
The name of this project is JEIExporter, not RecipeExporter. Only the display items of JEI can be exported, not the matching operation.
